/**
 * Default configuration for CRD schema sync
 */

import type { SyncConfig, CRDSource } from './types';
import { cac } from 'cac';
import { version } from '../package.json';

const DEFAULT_SOURCES: Array<CRDSource> = [
  {
    id: 'kong',
    name: 'Kong Ingress Controller',
    url: 'https://raw.githubusercontent.com/Kong/charts/main/charts/kong/crds/custom-resource-definitions.yaml',
    group: 'configuration.konghq.com',
    enabled: true,
  },
] as const;

const DEFAULT_CONFIG: SyncConfig = {
  sources: DEFAULT_SOURCES,
  targetRepo: 'datreeio/CRDs-catalog',
  targetBranch: 'main',
  createPR: false,
  prTitleTemplate: 'chore: sync {source} CRD schemas',
  prBodyTemplate: `## Automated CRD Schema Sync

This PR automatically updates JSON schemas for Kubernetes Custom Resource Definitions.

**Source**: {source}
**Schemas Updated**: {count}
**Timestamp**: {timestamp}

Generated by [\`k8s-crd-schema-sync\`](https://github.com/paambaati/k8s-crd-schema-sync)
`,
  dryRun: false,
  outputDir: './schemas',
  verbose: false,
} as const;

export function getDefaultConfig(): SyncConfig {
  return { ...DEFAULT_CONFIG };
}

export function loadConfigFromEnv(): Partial<SyncConfig> {
  return {
    createPR: process.env.CRD_SYNC_CREATE_PR === 'true',
    dryRun: process.env.CRD_SYNC_DRY_RUN === 'true',
    verbose: process.env.CRD_SYNC_VERBOSE === 'true',
    githubToken: process.env.GITHUB_TOKEN,
    outputDir: process.env.CRD_SYNC_OUTPUT_DIR || './schemas',
    targetRepo: process.env.CRD_SYNC_TARGET_REPO || 'datreeio/CRDs-catalog',
    targetBranch: process.env.CRD_SYNC_TARGET_BRANCH || 'main',
  };
}

export function mergeConfigs(base: SyncConfig, overrides: Partial<SyncConfig>): SyncConfig {
  return {
    ...base,
    ...overrides,
    sources: overrides.sources || base.sources,
  };
}

export function parseConfigFromCLI(args: Array<string>): {
  config: Partial<SyncConfig>;
  showHelp: boolean;
  showVersion: boolean;
} {
  const cli = cac('crd-schema-sync');

  // Register a default command with global options
  cli
    .command('', 'Sync CRD schemas')
    .option('--verbose', 'Enable verbose logging')
    .option('-d, --dry-run', 'Dry run mode (do not create PRs)')
    .option('-c, --create-pr', 'Create PR on target repository')
    .option('-o, --output-dir <path>', 'Output directory for schemas')
    .option('-t, --target-repo <repo>', 'Target GitHub repository')
    .option('-b, --target-branch <name>', 'Target branch')
    .allowUnknownOptions();

  cli.help();
  cli.version(version);

  const parsed = cli.parse(args, { run: false });

  const config: Partial<SyncConfig> = {};

  if (parsed.options.verbose) {
    config.verbose = true;
  }
  if (parsed.options.dryRun) {
    config.dryRun = true;
  }
  if (parsed.options.createPr) {
    config.createPR = true;
  }
  if (parsed.options.outputDir) {
    config.outputDir = parsed.options.outputDir as string;
  }
  if (parsed.options.targetRepo) {
    config.targetRepo = parsed.options.targetRepo as string;
  }
  if (parsed.options.targetBranch) {
    config.targetBranch = parsed.options.targetBranch as string;
  }

  const showHelp = args.includes('--help') || args.includes('-h');
  const showVersion = args.includes('--version');

  if (showHelp) {
    cli.outputHelp();
  }
  if (showVersion) {
    cli.outputVersion();
  }

  return { config, showHelp, showVersion };
}
